### ISSUE TITLE
Sale of devices with tasmota as part of a commercial product?

### ISSUE THREAD

**Issue by AlexObukhoff** [tasmota/install#1]
As part of my company's commercial product, it will be necessary to use a controlled wi-fi relay.  I'm going to use Tasmota as the software for these relays. 
Does the Tasmota license allow the sale of devices with it as part of a commercial product?

**Comment by Jason2866** [comment]
Tasmota uses this license https://github.com/arendst/Tasmota/blob/development/LICENSE.txt
