### ISSUE TITLE
contact only via discord

### ISSUE THREAD

**Issue by simcup** [tasmota/install#18]
hey, i just wanted to share my settings for a "Steckdosenleiste" sold under the brand of HAMA in germany (4 schuko sockets+4usb A ports) and the best to get in contact was to open a discord account. f* discord. 

HAMA Steckdosenleiste

schalter LED -> GPIO1
schalter Button GPI3
socket relay 1 -> GPIO5
socket relay 2 -> GPIO4
socket relay 3 -> GPIO12
socket relay 4 -> GPIO13
socket relay usb -> GPIO14

**Comment by sfromis** [comment]
The best way would be to submit a device template with the details.
https://templates.blakadder.com/new.html
