### ISSUE TITLE
Releases not standard?

### ISSUE THREAD

**Issue by dkebler** [tasmota/install#20]
I am trying to use this tool to grab the latest version of an asset binary but it doesn't work.
https://github.com/dvershinin/lastversion/

See here.

https://github.com/dvershinin/lastversion/discussions/116

Anything you can/willing to  "fix" at your end?

> Even with --pre  it won't work as you want, I guess, because all the latest "versions" are nothing but references to commits. To me, it looks like they are misusing release tags for tracking upstream commits, without providing a clear version string... probably won't be supported.

if you install lastversion and try 

`lastversion --pre tasmota/install`

you will get some "bogus"  version/release  `29`  which will then download a way old release from 2023

```
Program Version	12.4.0.2(lvgl-haspmota)
Build Date & Time	2023-03-13T15:09:39
```

without fix I have to manually download the binary I want to install and can't use that tool as part of an install script I have.

I could just as well use https://ota.tasmota.com/tasmota32/  but for some reason it does not include all the assest binaries available at tasmota/install.   Why is that?

In particular at this time I need `tasmotas2-lvgl.factory.bin` and that is not at https://ota.tasmota.com/tasmota32/ but is at https://github.com/tasmota/install/releases/tag/2024-08-01.d.836ce9ef9ba64677861a173cc7687be380acef6b

**Comment by Jason2866** [comment]
Sorry no, our resources are very limited and we can not implement support for the many existing tools out there. We do recommend to use the provided tools from Tasmota to install and update.
BTW. Using https://github.com/tasmota/install/releases/latest points to last release version.
Cant see anything wrong.
You can fetch https://github.com/tasmota/install/blob/main/tag.txt where all development commits are listed where a pre-release is available in release section.

**Comment by dkebler** [comment]
I know you closed this but a few points.   https://github.com/tasmota/install/releases/latest  only takes you to the latest release not the pre-releases.   That program "lastversion" works fine for your releases but not pre-releases which it does on other repos fine (like wled).  That is what he is saying about not having a proper "tag/pre-release".    Ok you can't do anything about it.

SO my issue is then.

I'd be happy to use a release instead of a pre-release but for whatever reason the release does NOT include `tasmota32s2-lvgl.factory.bin` but it is in the daily pre-releases.  Further I asked about about why   https://ota.tasmota.com/tasmota32/  which has daily releases does not match the pre-releases at github (i.e. there is NO `tasmota32s2-lvgl.factory.bin`).   Seems weird shouldn't the CI produce the same set of assets whether it is a pre-release or release?   

Anyway....can you get bins at  https://ota.tasmota.com/tasmota32/  to match the assets of the pre-release at github?  (i.e. include `tasmota32s2-lvgl.factory.bin` ?   If so my issue is solved cause I can just curl it.

**Comment by dkebler** [comment]
Came up with one liner that works so I'm good.

`
BIN=tasmota32s2-lvgl.factory.bin; wget $(curl --silent https://api.github.com/repos/tasmota/install/releases | grep "browser_download_url\": \"" | grep $BIN | head -1 | sed 's/^.*: //' | xargs)`

will download latest release pre or regular whichever is first from curl command

`https://github.com/tasmota/install/releases/download/2024-08-04.d.bdec6aed67387e4b1233c442ac77977665884c0e/tasmota32s2-lvgl.factory.bin`

**Comment by Jason2866** [comment]
The OTA server provides only the firmware variants build in official Tasmota repo.
CDN network traffic does cost money...
The Tasmota Install repo provides more build variants. All "unofficial" builds are available here. The `tasmota32s2-lvgl.factory.bin` is not a official standard build provided from Tasmota. That's why this variant is **not** included when tagged as release.
