### ISSUE TITLE
released version of tasmota32c3 crashes

### ISSUE THREAD

**Issue by Mape24** [tasmota/install#21]
Today I installed

`https://github.com/tasmota/install/tree/firmware/firmware/unofficial/tasmota32c3_2M.bin`  v.14.2.4
which works well.

The "official version"
`https://github.com/tasmota/install/tree/firmware/firmware/release/tasmota32c3.bin` 
crashes already after 4sec.

As the unofficial version seems to work well, this issue is probably solved.

**Comment by Mape24** [comment]
Sorry, I checked again. Error description is different. If I run the installer
`https://tasmota.github.io/install/  `
with any online Tasmota version, then the FW runs smoothly.

If I download the same file to local and try to upload this local file using the same tool, then it crashes after 4 sec.

So it rather seems to be a bug with the online installer.

**Comment by Jason2866** [comment]
The online installer only supports factory images
