### ISSUE TITLE
Temp Shows Input in Fahrenheit Shown in Celsius With °F 

### ISSUE THREAD

**Issue by ChipStewart1** [tasmota/install#7]
I installed Tasmota-thermostat.bin in a smart plug with two AM2301 / DHT21 sensors added (indoor & outdoor).  After entering THERMOSTATMODESET 1 in the console, I see it enabled with the temp in Celsius.  When I enter TEMPFORMATSET 1, the temperature is still in Celsius but is displayed followed by °F. I enter a target temp as TEMPTARGETSET 72 but it displays as 22.2 °F.  I tried SetOption8, but it didn't help. Any ideas?

ThermoSwitch
AM2301-04 Temperature	82.6 °F
AM2301-04 Humidity	        70.8 %
AM2301-04 Dew point	72.1 °F
AM2301-05 Temperature	87.3 °F
AM2301-05 Humidity	        62.4 %
AM2301-05 Dew point	72.8 °F
_______________________________________
Thermostat	                        Enabled
Set Point Temperature	22.2 °F
Current Temperature	        0.0 °F
Gradient Temperature	        0.0 °F
Duty cycle	                        66 %
Cycle time	                       30 Min
PI Auto tuning	               Disabled

Also, the sensors are on GPIO4 & GPIO5. The temps show fine at the top, but as 0° on the thermostat part. How can i assign the thermostat input as GPIO4?
Thanks,
Chip Stewart

**Comment by slonopotamus** [comment]
I thinks this is a wrong repository for such bugreport. This repo is dedicated to Tasmota web installer only.

**Comment by Jason2866** [comment]
If the problem still exists please open at https://github.com/arendst/Tasmota
This is only for issues with the Installer
