### ISSUE TITLE
custom firmware

### ISSUE THREAD

**Issue by joedupa** [tasmota/install#8]
Hi, thanks for your work. Is there any way to choose and flash a custom firmware compiled locally for specific development?

**Comment by Jason2866** [comment]
If you mean with Web Installer. No
Flashing locally is described in the Tasmota docu https://tasmota.github.io/docs/Getting-Started/#needed-hardware

**Comment by slonopotamus** [comment]
I +1, it would be nice if there was an input field to specify a custom local file to flash.

**Comment by Jason2866** [comment]
We are checking. Currently we cant say if it is possible. A complete rewrite will be necessary if we find a way...

**Comment by slonopotamus** [comment]
I guess, the main question is whether browsers support such usecase at all. User file from and `<input type=file>` needs somehow to be consumed by Web Serial API. That might work either directly, or via upload/download through server. Anyway, my knowledge is extremely shallow in this area, so I'm not sure it is possible.

**Comment by Jason2866** [comment]
Without changes in ESP Web tools there is no way to upload a user firmware file.

**Comment by Jason2866** [comment]
Closing, not possible.

**Comment by Jason2866** [comment]
@joedupa  Try https://tasmota.github.io/install/index_release.html
